### ISSUE TITLE
directions api re-runs

### ISSUE THREAD

**Issue by caitlynmralph** [the-pudding/pubs-viz#20]
under 25:
result-coordinates-navigationinn.txt
result-coordinates-cricketersarms.txt
result-coordinates-blackbullinn.txt
result-coordinates-commercialinn.txt
result-coordinates-orangetree.txt

over 25:
result-coordinates-bellinn-1.txt
result-coordinates-wheatsheafinn-1.txt
result-coordinates-whitehorseinn-2.txt
result-coordinates-nagshead-3.txt
result-coordinates-queenshead-7.txt
result-coordinates-princeofwales-6.txt
result-coordinates-shipinn-4.txt
result-coordinates-blackbull-2.txt
result-coordinates-swaninn-4.txt
result-coordinates-swaninn-5.txt

**Comment by jadiehm** [comment]
result-coordinates-inn-1.txt
result-coordinates-inn-2.txt

**Comment by jadiehm** [comment]
frankie&benny's.txt
